### ISSUE TITLE
Change the spreading factor

### ISSUE THREAD

**Issue by fortudiego** [ARMmbed/mbed-os-example-lorawan#139]
Hi I'm using your code and everything works correctly, but I would like to increase the spreading factor (SF) that I saw to be default to 7. How can I do ??

Thanks for the attention

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2001

**Comment by fortudiego** [comment]
I will be very grateful if you could send me the right link. I'm not able to find it
Thanking in advance.

**Comment by AnttiKauppila** [comment]
See https://github.com/ARMmbed/mbed-os/blob/master/features/lorawan/LoRaWANInterface.h#L213
And https://github.com/ARMmbed/mbed-os/blob/master/features/lorawan/lorawan_types.h#L354 onwards

**Comment by AnttiKauppila** [comment]
Also ADR must be switched off

**Comment by AnttiKauppila** [comment]
“At this time, due to our prioritisation of work on customer projects, we are unable to devote the time to fix this issue. As an open source project, we welcome fixes to Mbed OS, so if would like to contribute a fix yourself then we would very much welcome that, please see our contribution guidelines here - https://os.mbed.com/docs/mbed-os/v5.14/contributing/workflow.html#contributions”
