### ISSUE TITLE
Can't receive downlink message

### ISSUE THREAD

**Issue by cipiasentini** [ARMmbed/mbed-os-example-lorawan#152]
I am using a Multitech mDot with the development kit (this one https://www.multitech.com/brands/mdot-devkit) and I'm compiling for this version **MTS_MDOT_F411RE**. Uplink works just fine (kind of, sometimes there are some packages missed, the debug tool says that the delivery was done but I don't receive it on the gateway).
Appart from this issue, I am not able to send data from the gateway (neither confirmed nor unconfirmed) I on the debugger I get no notification of receipt and on the gateway the downlink packages get cancelled after a while. What could the problem be? On the firmware I also tried to set up a port number (different from the uplink one) for the receive_message() function, but this shouldn't be done according to the documentation on the Lorawaninterface.h. I'd appreciate any help. Thanks

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2100

**Comment by AnttiKauppila** [comment]
“At this time, due to our prioritisation of work on customer projects, we are unable to devote the time to fix this issue. As an open source project, we welcome fixes to Mbed OS, so if would like to contribute a fix yourself then we would very much welcome that, please see our contribution guidelines here - https://os.mbed.com/docs/mbed-os/v5.14/contributing/workflow.html#contributions”
